/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModuloAnaliticoRouteImport } from './routes/modulo-analitico'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PesquisadorIdRouteImport } from './routes/pesquisador.$id'

const ModuloAnaliticoRoute = ModuloAnaliticoRouteImport.update({
  id: '/modulo-analitico',
  path: '/modulo-analitico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisadorIdRoute = PesquisadorIdRouteImport.update({
  id: '/pesquisador/$id',
  path: '/pesquisador/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modulo-analitico': typeof ModuloAnaliticoRoute
  '/pesquisador/$id': typeof PesquisadorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modulo-analitico': typeof ModuloAnaliticoRoute
  '/pesquisador/$id': typeof PesquisadorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modulo-analitico': typeof ModuloAnaliticoRoute
  '/pesquisador/$id': typeof PesquisadorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modulo-analitico' | '/pesquisador/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modulo-analitico' | '/pesquisador/$id'
  id: '__root__' | '/' | '/modulo-analitico' | '/pesquisador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModuloAnaliticoRoute: typeof ModuloAnaliticoRoute
  PesquisadorIdRoute: typeof PesquisadorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modulo-analitico': {
      id: '/modulo-analitico'
      path: '/modulo-analitico'
      fullPath: '/modulo-analitico'
      preLoaderRoute: typeof ModuloAnaliticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisador/$id': {
      id: '/pesquisador/$id'
      path: '/pesquisador/$id'
      fullPath: '/pesquisador/$id'
      preLoaderRoute: typeof PesquisadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModuloAnaliticoRoute: ModuloAnaliticoRoute,
  PesquisadorIdRoute: PesquisadorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
