x-test-variables: &test
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_DB: postgres
    PG_HOST: tees-test-pgvector
    PG_PORT: 5432
  networks:
    - tees-network

x-dev-variables: &dev
  environment:
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
    POSTGRES_DB: ${POSTGRES_DB:-postgres}
    PG_HOST: ${PG_HOST:-localhost}
    PG_PORT: ${PG_PORT:-5432}

services:
  tees-test:
    build: .
    command: ["uv", "run", "pytest", "--cov", "--durations=0"]
    <<: *test
    networks:
      - tees-network

  tees-lint:
    build: .
    command: ["uv", "run", "ty", "check"]
    <<: *test
    networks:
      - tees-network

  tees-test-migrations:
    build: .
    command: ["uv", "run", "src/migrate.py"]
    <<: *test
    networks:
      - tees-network

  tees-test-pgvector:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tees-network
    <<: *test

  tees-pgvector:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    volumes:
      - tees_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${PG_PORT:-5432}:5432
    <<: *dev
    networks:
      - tees-network

  tees-migrations:
    build: .
    command: ["uv", "run", "src/migrate.py"]
    network_mode: host
    <<: *dev

volumes:
  tees_data:

networks:
  tees-network:
