-- 
-- depends: 

CREATE TABLE researcher (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	full_name TEXT NOT NULL,
	filename TEXT NOT NULL,
	filehash TEXT NOT NULL
);

CREATE TABLE papers (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	title TEXT NOT NULL,
	researcher_id INTEGER NOT NULL,
	FOREIGN KEY(researcher_id) REFERENCES researcher(id)
);
