name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          DIMENSIONS: ${{ secrets.DIMENSIONS }}
        run: |
          chmod +x ./scripts/ci.sh
          ./scripts/ci.sh
